name: xeus
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - pkg-config
  # Host dependencies
  - zeromq=4.3.3
  - zeromq-static=4.3.3 
  - cppzmq=4.7.1
  - xtl=0.7
  - OpenSSL=1 
  - libopenssl-static=1
  - nlohmann_json
  # Test dependencies
  - pytest
  - jupyter_kernel_test=0.3.0
