jobs:
  - job: 'Linux'
    strategy:
      matrix:
        shared:
          xeus_static_dependencies: 0
          xeus_build_shared_lib: 1
        static:
          xeus_static_dependencies: 1
          xeus_build_shared_lib: 0
    pool:
      vmImage: ubuntu-16.04
    timeoutInMinutes: 30
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
        parameters:
          platform: 'Linux'
