parameters:
  - name: 'platform'
    type: string

steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      source activate xeus
      conda install gxx_linux-64=7.3 libgcc=7.2 libuuid -c conda-forge
    condition: eq('${{ parameters.platform }}', 'Linux')
    displayName: Install conda-forge compilers

  - script: |
      source activate xeus
      mkdir build
      cd build
      if [[ $(xeus_static_dependencies) == '1' ]]; then
        CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DXEUS_STATIC_DEPENDENCIES=ON";
      fi
      if [[ $(xeus_build_shared_lib) == '0' ]]; then
        CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DXEUS_BUILD_SHARED_LIBS=OFF";
      fi
      cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DXEUS_DOWNLOAD_GTEST=ON -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX $CMAKE_EXTRA_ARGS $(Build.SourcesDirectory)
    displayName: Configure xeus
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate xeus
      make install -j2
    displayName: Build xeus
    workingDirectory: $(Build.BinariesDirectory)/build

  - script: |
      source activate xeus
      ctest --output-on-failure
    displayName: Test xeus
    workingDirectory: $(Build.BinariesDirectory)/build/test
